import type { ReviewItem, ReviewPayload } from "../app/types";

type SeedReview = Omit<ReviewItem, "payload" | "latestDecision" | "diagnosisDecisions" | "jiraTickets"> & {
  payload: ReviewPayload;
};

export const seedReviews: SeedReview[] = [
  {
    incidentId: "INC-2847",
    title: "Checkout requests timing out after gateway rollout",
    application: "InsuranceCallCenter",
    environment: "Production",
    severity: "SEV-1",
    symptom: "Payment authorization requests are exceeding the 8-second SLO across three regions.",
    reviewStatus: "pending",
    diagnosisCount: 3,
    topConfidence: 0.86,
    createdAt: "2026-09-04T14:16:00Z",
    payload: {
      dataOrigin: "synthetic",
      sourceProject: "InsuranceCallCenter",
      scenarioBasis: "Modeled from the FastAPI-to-agent-message integration and its CockroachDB-backed request flow. All values and log lines are fabricated.",
      detectedAt: "14:16 UTC · 12 min ago",
      service: "payment-orchestrator",
      owner: "Payments Platform",
      affected: "31% of checkout sessions",
      diagnoses: [
        {
          id: "DX-2847-A",
          title: "Database connection pool exhaustion",
          summary: "A traffic burst combined with longer transaction duration saturated the Hikari pool, causing request threads to queue until timeout.",
          confidence: 0.86,
          evidenceIds: ["E1", "E4", "E7"],
          signals: ["Pool active=50/50", "Pending threads peaked at 118", "Latency tracks pool saturation"],
        },
        {
          id: "DX-2847-B",
          title: "TLS regression in the gateway client",
          summary: "The rollout may have introduced handshake retries, increasing connection hold time and indirectly exhausting the pool.",
          confidence: 0.48,
          evidenceIds: ["E2", "E6"],
          signals: ["Handshake warnings began after deploy", "No certificate expiry observed"],
        },
        {
          id: "DX-2847-C",
          title: "Upstream rate limiting",
          summary: "429 responses from the payment gateway could explain retries, but the rate is too low to explain the full impact.",
          confidence: 0.24,
          evidenceIds: ["E5"],
          signals: ["Small 429 spike", "Does not precede first timeout"],
        },
      ],
      suggestedChanges: [
        {
          id: "CH-41",
          diagnosisId: "DX-2847-A",
          title: "Reduce transaction hold time",
          detail: "Move the gateway call outside the database transaction and verify connection release on timeout paths.",
          risk: "Medium",
          category: "Code",
          files: ["src/main/java/com/acme/payments/PaymentAuthorizationService.java"],
          implementation: "Keep only the database write inside the transaction. Perform the remote authorization first, then open a short transaction to persist the confirmed result. Preserve the existing timeout and error mapping behavior.",
          language: "java",
          code: `GatewayResult result = gatewayClient.authorize(request);

transactionTemplate.executeWithoutResult(status -> {
  authorizationRepository.save(
    Authorization.from(request, result)
  );
});`,
          validation: "Run payment-orchestrator integration tests, then load-test at 2x the observed peak. Confirm connection acquisition p95 stays below 100 ms and pending threads remain below 20.",
          rollback: "Revert the transaction-boundary commit and restore the previous deployment. No data migration is required.",
        },
        {
          id: "CH-42",
          diagnosisId: "DX-2847-A",
          title: "Add pool-saturation guardrail",
          detail: "Alert when pending threads exceed 20 for three minutes and expose acquisition latency by endpoint.",
          risk: "Low",
          category: "Observability",
          files: ["src/main/resources/application.yml", "observability/payment-orchestrator-alerts.yml"],
          implementation: "Publish Hikari pending-thread and acquisition-duration metrics with endpoint labels. Add a warning alert at 20 pending threads for three minutes and a critical alert at 40.",
          code: `- alert: PaymentPoolSaturation
  expr: hikaricp_connections_pending{service="payment-orchestrator"} > 20
  for: 3m
  labels:
    severity: warning`,
          language: "yaml",
          validation: "Trigger the alert in staging with a controlled pool limit and verify the dashboard links to the affected endpoint.",
          rollback: "Remove the alert rule if it produces sustained false positives; metric publication can remain enabled.",
        },
        {
          id: "CH-43",
          diagnosisId: "DX-2847-B",
          title: "Validate gateway client rollout",
          detail: "Compare TLS handshake duration before and after release 2026.09.04.2; roll back only after confirmation.",
          risk: "Low",
          category: "Validation",
          implementation: "Run the existing gateway canary against both client versions and compare TLS handshake p50, p95, and retry counts over a 15-minute window.",
          validation: "Treat the rollout as causal only if the new client shows a statistically meaningful increase and the old canary remains within baseline.",
          rollback: "Restore gateway-client 4.8.1 through the standard deployment pipeline.",
        },
      ],
      similarIncidents: [
        {
          id: "INC-1932",
          title: "Order service pool starvation",
          similarity: 0.91,
          resolution: "Shortened transaction boundary and added acquisition alerts.",
          age: "47 days ago",
        },
        {
          id: "INC-1764",
          title: "Gateway retry amplification",
          similarity: 0.73,
          resolution: "Capped retries and added jittered backoff.",
          age: "3 months ago",
        },
      ],
      evidence: [
        { id: "E1", time: "14:15:42", source: "application.log", detail: "HikariPool-1 — Connection is not available, request timed out after 3000ms", tone: "critical" },
        { id: "E2", time: "14:15:29", source: "gateway.log", detail: "TLS handshake duration crossed 900ms p95 after deployment", tone: "warning" },
        { id: "E4", time: "14:14:58", source: "metrics", detail: "db.pool.active reached configured maximum of 50", tone: "critical" },
        { id: "E7", time: "14:13:21", source: "source", detail: "Remote authorization occurs inside @Transactional method", tone: "info" },
      ],
    },
  },
  {
    incidentId: "INC-2843",
    title: "Address normalization returning partial results",
    application: "AddressStandardizationAPI",
    environment: "Production",
    severity: "SEV-2",
    symptom: "Canadian addresses intermittently return without postal-code normalization.",
    reviewStatus: "pending",
    diagnosisCount: 2,
    topConfidence: 0.72,
    createdAt: "2026-09-04T13:41:00Z",
    payload: {
      dataOrigin: "synthetic",
      sourceProject: "AddressStandardizationAPI",
      scenarioBasis: "Modeled from the Java address-provider contract and Canadian address mapping. All values and log lines are fabricated.",
      detectedAt: "13:41 UTC · 47 min ago",
      service: "address-standardizer",
      owner: "Customer Data",
      affected: "8.4% of Canadian submissions",
      diagnoses: [
        { id: "DX-2843-A", title: "Provider response schema drift", summary: "A newly optional postal_code field is skipped by the strict response mapper.", confidence: 0.72, evidenceIds: ["E1", "E3"], signals: ["Missing field begins at provider release", "US responses unaffected"] },
        { id: "DX-2843-B", title: "Regional cache inconsistency", summary: "One cache node may still serve an older normalization ruleset.", confidence: 0.39, evidenceIds: ["E2"], signals: ["Failures cluster in one region"] },
      ],
      suggestedChanges: [
        { id: "CH-31", diagnosisId: "DX-2843-A", title: "Make postal-code mapping tolerant", detail: "Accept absent provider fields and preserve the submitted value with a validation flag.", risk: "Low", category: "Code", files: ["src/mappers/provider-address.mapper.ts"], implementation: "Treat postal_code as optional at the provider boundary. Fall back to the submitted postal code and mark the response as requiring downstream validation.", language: "typescript", code: `const postalCode = provider.postal_code ?? request.postalCode;
return { ...mapped, postalCode, postalCodeVerified: Boolean(provider.postal_code) };`, validation: "Add contract fixtures for missing, null, and valid postal_code values; run the Canadian address regression suite.", rollback: "Revert the mapper change; no persisted schema is affected." },
        { id: "CH-32", diagnosisId: "DX-2843-B", title: "Compare cache ruleset versions", detail: "Verify ruleset hashes across all regional cache nodes before invalidation.", risk: "Low", category: "Validation", implementation: "Query the ruleset version endpoint on every regional node and compare its hash with the expected release manifest before taking any invalidation action.", validation: "All nodes should report the same ruleset hash for two consecutive checks.", rollback: "No rollback is required because this step is read-only." },
      ],
      similarIncidents: [
        { id: "INC-1621", title: "Province field omitted by provider", similarity: 0.79, resolution: "Introduced tolerant parsing and schema-contract alerts.", age: "5 months ago" },
      ],
      evidence: [
        { id: "E1", time: "13:40:51", source: "application.log", detail: "Mapping warning: postal_code absent from provider response", tone: "warning" },
        { id: "E2", time: "13:39:16", source: "metrics", detail: "Failure rate concentrated in ca-central routing pool", tone: "info" },
        { id: "E3", time: "13:37:03", source: "deployment", detail: "Provider API schema version changed from 2.6 to 2.7", tone: "critical" },
      ],
    },
  },
  {
    incidentId: "INC-2838",
    title: "Duplicate policy messages on retry",
    application: "InsuranceAgentMessageService",
    environment: "Staging",
    severity: "SEV-3",
    symptom: "A subset of retried policy events produces duplicate outbound notifications.",
    reviewStatus: "pending",
    diagnosisCount: 1,
    topConfidence: 0.94,
    createdAt: "2026-09-04T11:52:00Z",
    payload: {
      dataOrigin: "synthetic",
      sourceProject: "InsuranceAgentMessageService",
      scenarioBasis: "Modeled from the durable queue, idempotency, and retry architecture. All values and log lines are fabricated.",
      detectedAt: "11:52 UTC · 2 hr ago",
      service: "agent-message-worker",
      owner: "Agent Experience",
      affected: "14 duplicate notifications",
      diagnoses: [
        { id: "DX-2838-A", title: "Idempotency key written after publish", summary: "A worker crash between publish and key persistence allows the same event to be emitted during retry.", confidence: 0.94, evidenceIds: ["E1", "E2", "E4"], signals: ["Same event ID published twice", "Crash occurs before idempotency write"] },
      ],
      suggestedChanges: [
        { id: "CH-21", diagnosisId: "DX-2838-A", title: "Use transactional outbox", detail: "Commit message intent and idempotency record atomically, then publish from the outbox.", risk: "Medium", category: "Architecture", files: ["src/workers/policy-event.worker.ts", "src/outbox/outbox.repository.ts", "migrations/20260904_add_outbox.sql"], implementation: "In one database transaction, reserve the idempotency key and insert an outbox row. A separate publisher claims unpublished rows and records completion only after broker acknowledgement.", language: "sql", code: `INSERT INTO message_outbox (event_id, topic, payload)
VALUES (:event_id, 'agent-notifications', :payload)
ON CONFLICT (event_id) DO NOTHING;`, validation: "Crash the worker after commit but before publish, restart it, and verify exactly one notification is emitted for the event ID.", rollback: "Disable the outbox publisher feature flag and return to the existing publisher; retain the table for forensic inspection." },
      ],
      similarIncidents: [],
      evidence: [
        { id: "E1", time: "11:51:48", source: "message.log", detail: "Published event EVT-7814 to agent-notifications", tone: "critical" },
        { id: "E2", time: "11:51:49", source: "worker.log", detail: "Process terminated before idempotency checkpoint", tone: "warning" },
        { id: "E4", time: "11:52:04", source: "message.log", detail: "Published event EVT-7814 to agent-notifications", tone: "critical" },
      ],
    },
  },
  {
    incidentId: "INC-2854",
    title: "Urgent agent messages remain queued",
    application: "InsuranceAgentMessageService",
    environment: "Production",
    severity: "SEV-1",
    symptom: "Urgent call-center notifications are accepted with HTTP 202 but do not reach agent inboxes.",
    reviewStatus: "pending",
    diagnosisCount: 3,
    topConfidence: 0.89,
    createdAt: "2026-09-04T15:04:00Z",
    payload: {
      dataOrigin: "synthetic",
      sourceProject: "InsuranceAgentMessageService",
      scenarioBasis: "Modeled from the real scheduled worker, queue status lifecycle, and CockroachDB lease implementation. All telemetry is fabricated.",
      detectedAt: "15:04 UTC · 4 min ago",
      service: "agent-message-worker",
      owner: "Agent Communications",
      affected: "186 queued messages; 41 urgent",
      diagnoses: [
        { id: "DX-2854-A", title: "Queue worker disabled in runtime configuration", summary: "The API continues accepting durable requests while the scheduled consumer is disabled, allowing a queue backlog with no delivery attempts.", confidence: 0.89, evidenceIds: ["E1", "E2", "E5"], signals: ["202 responses remain healthy", "No claim logs after restart", "attempts stays at zero"] },
        { id: "DX-2854-B", title: "Database contention prevents queue claims", summary: "Repeated CockroachDB serialization conflicts may exhaust claim retries before a worker acquires any item.", confidence: 0.57, evidenceIds: ["E3", "E6"], signals: ["SQLSTATE 40001 observed", "Claim latency increased"] },
        { id: "DX-2854-C", title: "Priority ordering starves normal messages", summary: "A continuous urgent-message stream could delay lower priorities, but it does not explain urgent items with zero attempts.", confidence: 0.21, evidenceIds: ["E4"], signals: ["Backlog includes normal priority", "Urgent items also stationary"] },
      ],
      suggestedChanges: [
        { id: "CH-54", diagnosisId: "DX-2854-A", title: "Enable and health-check the queue worker", detail: "Restore the worker flag and expose queue-consumer readiness separately from API health.", risk: "Low", category: "Configuration", files: ["src/main/resources/application.yml", "src/main/java/com/propertycasualty/agentmessage/service/AgentMessageQueueWorker.java"], implementation: "Set the production worker flag explicitly and add a readiness indicator containing last successful poll time and backlog age.", language: "yaml", code: `agent-message:\n  worker:\n    enabled: true\n    poll-delay-ms: 1000\n    batch-size: 10`, validation: "Send one synthetic urgent message and confirm QUEUED → PROCESSING → DELIVERED with attempts=1, then verify backlog age decreases.", rollback: "Disable the worker only if delivery errors accelerate; accepted requests remain durable in the queue." },
        { id: "CH-55", diagnosisId: "DX-2854-B", title: "Instrument claim retry exhaustion", detail: "Emit a counter and alert when Cockroach serialization retries fail to acquire work.", risk: "Low", category: "Observability", files: ["src/main/java/com/propertycasualty/agentmessage/service/QueueTransactions.java"], implementation: "Count SQLSTATE 40001 retries and exhausted claim operations without changing the existing transaction boundary.", validation: "Create controlled contention in staging and confirm retry and exhaustion metrics match logged attempts.", rollback: "Remove the metric instrumentation; queue semantics are unchanged." },
      ],
      similarIncidents: [
        { id: "INC-2838", title: "Duplicate policy messages on retry", similarity: 0.68, resolution: "Reviewed idempotency and delivery transaction boundaries.", age: "Earlier today" },
        { id: "INC-2087", title: "Notification consumer disabled after maintenance", similarity: 0.86, resolution: "Restored worker enablement and added consumer-specific readiness.", age: "29 days ago" },
      ],
      evidence: [
        { id: "E1", time: "15:03:52", source: "api.log", detail: "POST /api/v1/agent-messages returned 202 status=QUEUED", tone: "info" },
        { id: "E2", time: "15:03:40", source: "queue.metrics", detail: "oldest_ready_item_seconds=742; delivery_rate=0", tone: "critical" },
        { id: "E3", time: "15:02:18", source: "database.log", detail: "Synthetic sample: restart transaction SQLSTATE 40001 during claim", tone: "warning" },
        { id: "E4", time: "15:01:44", source: "queue.metrics", detail: "ready backlog urgent=41 high=63 normal=82", tone: "warning" },
        { id: "E5", time: "14:51:02", source: "deployment", detail: "Worker pod restarted with AGENT_MESSAGE_WORKER_ENABLED=false", tone: "critical" },
        { id: "E6", time: "14:49:28", source: "database.metrics", detail: "transaction retry rate increased to synthetic value 3.2%", tone: "info" },
      ],
    },
  },
  {
    incidentId: "INC-2853",
    title: "Agent updates fail during address validation",
    application: "PropertyCasualtyInsuranceAgentInfo",
    environment: "Production",
    severity: "SEV-2",
    symptom: "Creating or updating agents returns 503 before changes are persisted when an address is supplied.",
    reviewStatus: "pending",
    diagnosisCount: 3,
    topConfidence: 0.84,
    createdAt: "2026-09-04T14:58:00Z",
    payload: {
      dataOrigin: "synthetic",
      sourceProject: "PropertyCasualtyInsuranceAgentInfo",
      scenarioBasis: "Modeled from the real FastAPI address-standardization client and its separate Java dependency. No production request or address is used.",
      detectedAt: "14:58 UTC · 10 min ago",
      service: "property-agent-api",
      owner: "Agency Operations",
      affected: "23 agent and service-center writes",
      diagnoses: [
        { id: "DX-2853-A", title: "Address service credentials differ after rotation", summary: "The Python caller and Java address API were deployed with different Basic Auth values, so every standardization request is rejected.", confidence: 0.84, evidenceIds: ["E1", "E2", "E4"], signals: ["Downstream returns 401", "Health endpoint remains available", "Failures began at credential rotation"] },
        { id: "DX-2853-B", title: "Address API is unreachable", summary: "A connection or DNS failure maps to the same user-facing 503 response, but downstream access logs show requests arriving.", confidence: 0.33, evidenceIds: ["E3"], signals: ["TCP connection succeeds", "Actuator health is UP"] },
        { id: "DX-2853-C", title: "Geocoding provider timeout", summary: "Provider timeouts can fail writes, but this incident ends at the service authentication layer before a provider call.", confidence: 0.16, evidenceIds: ["E5"], signals: ["No provider request recorded", "Failure latency below connect timeout"] },
      ],
      suggestedChanges: [
        { id: "CH-53", diagnosisId: "DX-2853-A", title: "Rotate the shared credential atomically", detail: "Update both services from the same secret version and verify authentication before routing user traffic.", risk: "Low", category: "Configuration", files: ["PropertyCasualtyInsuranceAgentInfo/backend/.env", "AddressStandardizationAPI runtime environment"], implementation: "Reference one managed secret version from both deployments. Keep secret values out of source and logs, and gate rollout on an authenticated synthetic request.", validation: "Submit a non-customer test address and confirm the caller receives a standardized response without logging the Authorization header.", rollback: "Point both deployments back to the previous secret version during the rotation overlap window." },
        { id: "CH-52", diagnosisId: "DX-2853-B", title: "Add dependency-specific readiness", detail: "Expose address-service reachability separately from base API liveness.", risk: "Low", category: "Observability", files: ["PropertyCasualtyInsuranceAgentInfo/backend/main.py"], implementation: "Report the downstream dependency state without sending credentials or real address data in the health request.", validation: "Block port 8081 in staging and verify readiness fails while liveness stays healthy.", rollback: "Remove the readiness check if it destabilizes deployment orchestration." },
      ],
      similarIncidents: [
        { id: "INC-2843", title: "Address normalization returning partial results", similarity: 0.64, resolution: "Hardened the provider response boundary.", age: "Earlier today" },
        { id: "INC-2210", title: "Inter-service password rotation mismatch", similarity: 0.92, resolution: "Moved both workloads to a versioned shared secret rollout.", age: "18 days ago" },
      ],
      evidence: [
        { id: "E1", time: "14:57:42", source: "property-agent.log", detail: "Address standardization provider rejected request; surfaced as HTTP 503", tone: "critical" },
        { id: "E2", time: "14:57:42", source: "address-api.access", detail: "POST /api/v1/addresses/standardize returned 401", tone: "critical" },
        { id: "E3", time: "14:56:10", source: "synthetic-probe", detail: "GET /actuator/health returned UP in 31ms", tone: "info" },
        { id: "E4", time: "14:47:03", source: "deployment", detail: "Property-agent backend secret version advanced independently", tone: "warning" },
        { id: "E5", time: "14:46:59", source: "provider.metrics", detail: "No matching geocoding provider request observed", tone: "info" },
      ],
    },
  },
  {
    incidentId: "INC-2852",
    title: "Call-center notifications rejected by message service",
    application: "InsuranceCallCenter",
    environment: "Production",
    severity: "SEV-2",
    symptom: "Contact records save successfully, but Notify Agent returns 502 and leaves notification status as Failed.",
    reviewStatus: "pending",
    diagnosisCount: 2,
    topConfidence: 0.91,
    createdAt: "2026-09-04T14:43:00Z",
    payload: {
      dataOrigin: "synthetic",
      sourceProject: "InsuranceCallCenter",
      scenarioBasis: "Modeled from the real FastAPI agent_messaging client, API-key header, and retry-safe notification sequence. No customer data is represented.",
      detectedAt: "14:43 UTC · 25 min ago",
      service: "insurance-call-center-api",
      owner: "Call Center Platform",
      affected: "17 failed agent handoffs",
      diagnoses: [
        { id: "DX-2852-A", title: "Message-service API key missing from caller", summary: "The downstream service requires X-API-Key, but the call-center process started without AGENT_MESSAGE_API_KEY and omits the header.", confidence: 0.91, evidenceIds: ["E1", "E2", "E3"], signals: ["Downstream HTTP 401", "Header absent in sanitized trace", "Contact commit still succeeds"] },
        { id: "DX-2852-B", title: "Incorrect downstream base URL", summary: "A wrong service URL would cause an availability error rather than the observed authenticated endpoint response.", confidence: 0.22, evidenceIds: ["E4"], signals: ["Request reaches expected service", "Route path is correct"] },
      ],
      suggestedChanges: [
        { id: "CH-50", diagnosisId: "DX-2852-A", title: "Require the message key at startup", detail: "Fail readiness when production enables downstream authentication but the caller lacks its key.", risk: "Low", category: "Code", files: ["InsuranceCallCenter/backend/agent_messaging.py", "InsuranceCallCenter/backend/main.py"], implementation: "Validate required integration settings during startup and expose only configuration presence—not secret values—in readiness output.", language: "python", code: `settings = Settings.from_environment()\nif environment == "production" and not settings.api_key:\n    raise RuntimeError("AGENT_MESSAGE_API_KEY is required")`, validation: "Start a staging instance without the key and confirm it does not become ready; then supply the matching secret and send one synthetic notification.", rollback: "Temporarily relax readiness while restoring the prior secret, without disabling downstream authentication." },
        { id: "CH-51", diagnosisId: "DX-2852-A", title: "Alert on failed handoff status", detail: "Count call-center contacts entering notification_status=Failed and link the alert to downstream response class.", risk: "Low", category: "Observability", files: ["InsuranceCallCenter/backend/services.py"], implementation: "Increment a failure counter after the durable contact commit and before returning the sanitized 502 response.", validation: "Mock one downstream 401 and confirm the contact remains saved, status becomes Failed, and the alert dimension is authentication.", rollback: "Remove the new metric if label cardinality exceeds the agreed bound." },
      ],
      similarIncidents: [
        { id: "INC-2210", title: "Inter-service password rotation mismatch", similarity: 0.81, resolution: "Coordinated deployment of a versioned shared secret.", age: "18 days ago" },
      ],
      evidence: [
        { id: "E1", time: "14:42:55", source: "call-center.log", detail: "Message service returned synthetic HTTP 401; contact notification marked Failed", tone: "critical" },
        { id: "E2", time: "14:42:55", source: "message-service.access", detail: "POST /api/v1/agent-messages rejected: API key required", tone: "critical" },
        { id: "E3", time: "14:42:54", source: "database.audit", detail: "cc_contact commit completed before notification attempt", tone: "info" },
        { id: "E4", time: "14:42:54", source: "network.trace", detail: "Request reached expected service and API route", tone: "info" },
      ],
    },
  },
  {
    incidentId: "INC-2851",
    title: "Address API error rate spikes under provider throttling",
    application: "AddressStandardizationAPI",
    environment: "Production",
    severity: "SEV-2",
    symptom: "Valid US and Canadian addresses intermittently return 502 during a burst of agent updates.",
    reviewStatus: "pending",
    diagnosisCount: 3,
    topConfidence: 0.82,
    createdAt: "2026-09-04T14:25:00Z",
    payload: {
      dataOrigin: "synthetic",
      sourceProject: "AddressStandardizationAPI",
      scenarioBasis: "Modeled from the real Spring RestClient provider call, configured timeouts, and exception mapping. Provider responses are simulated.",
      detectedAt: "14:25 UTC · 43 min ago",
      service: "address-standardization-api",
      owner: "Platform Integrations",
      affected: "12.7% of standardization requests",
      diagnoses: [
        { id: "DX-2851-A", title: "Provider rate limiting mapped to generic 502", summary: "A request burst exceeds the external geocoding quota; the client surfaces the provider exception without bounded retry or a distinct throttle signal.", confidence: 0.82, evidenceIds: ["E1", "E2", "E5"], signals: ["Failures align with burst", "Provider response class is 429", "Health endpoint stays UP"] },
        { id: "DX-2851-B", title: "Read timeout too short for provider latency", summary: "The configured read timeout may cut off slow calls, but most failed requests return before the timeout threshold.", confidence: 0.41, evidenceIds: ["E3"], signals: ["p99 approaches timeout", "429 failures complete quickly"] },
        { id: "DX-2851-C", title: "Invalid provider API credential", summary: "Credential failures would be sustained rather than correlated with traffic bursts and successful requests between errors.", confidence: 0.14, evidenceIds: ["E4"], signals: ["Successful provider responses continue", "No sustained 401/403 class"] },
      ],
      suggestedChanges: [
        { id: "CH-48", diagnosisId: "DX-2851-A", title: "Handle throttling with bounded backoff", detail: "Recognize provider throttling, honor retry guidance, and cap attempts within the request latency budget.", risk: "Medium", category: "Code", files: ["AddressStandardizationAPI/src/main/java/com/harborpoint/address/geocodio/GeocodioClient.java"], implementation: "Add a narrowly scoped retry policy for 429 and transient 5xx responses. Use jitter, a strict attempt cap, and never retry validation failures.", language: "java", code: `return retryTemplate.execute(context ->\n    geocodioRestClient.get()\n        .uri(buildUri(request, country))\n        .retrieve()\n        .body(GeocodioResponse.class));`, validation: "Simulate 429, 429, 200 and verify bounded recovery; verify 4xx validation responses are attempted only once.", rollback: "Disable retries through configuration and return to single-attempt provider calls." },
        { id: "CH-49", diagnosisId: "DX-2851-B", title: "Separate timeout and throttle telemetry", detail: "Publish provider outcome class and latency without recording address fields.", risk: "Low", category: "Observability", files: ["AddressStandardizationAPI/src/main/java/com/harborpoint/address/geocodio/GeocodioClient.java"], implementation: "Record outcome counters for success, throttle, timeout, provider error, and configuration error with a low-cardinality country tag.", validation: "Run simulated provider outcomes and confirm dashboards distinguish fast throttles from read timeouts.", rollback: "Remove the new meters; provider behavior is unchanged." },
      ],
      similarIncidents: [
        { id: "INC-2843", title: "Address normalization returning partial results", similarity: 0.58, resolution: "Added tolerant provider-contract handling.", age: "Earlier today" },
        { id: "INC-1998", title: "External verification quota exhausted", similarity: 0.87, resolution: "Added quota alerts and bounded retry with jitter.", age: "52 days ago" },
      ],
      evidence: [
        { id: "E1", time: "14:24:57", source: "address-api.log", detail: "Synthetic provider exception while processing geocode request", tone: "critical" },
        { id: "E2", time: "14:24:56", source: "provider.trace", detail: "Simulated upstream response status=429 retry-after=1", tone: "critical" },
        { id: "E3", time: "14:24:10", source: "latency.metrics", detail: "provider p99=7.4s against configured 8s read timeout", tone: "warning" },
        { id: "E4", time: "14:23:46", source: "provider.metrics", detail: "Successful requests continue between failures", tone: "info" },
        { id: "E5", time: "14:22:59", source: "traffic.metrics", detail: "request rate increased 3.6x during batch update", tone: "warning" },
      ],
    },
  },
  {
    incidentId: "INC-2849",
    title: "Agent API latency rises while metrics snapshots are written",
    application: "PropertyCasualtyInsuranceAgentInfo",
    environment: "Staging",
    severity: "SEV-3",
    symptom: "CRUD request latency increases in lockstep with writes to the server metrics JSON snapshot.",
    reviewStatus: "pending",
    diagnosisCount: 2,
    topConfidence: 0.78,
    createdAt: "2026-09-04T14:02:00Z",
    payload: {
      dataOrigin: "synthetic",
      sourceProject: "PropertyCasualtyInsuranceAgentInfo",
      scenarioBasis: "Modeled from the real synchronous metrics registry, process lock, and atomic JSON file replacement. Timing measurements are fabricated.",
      detectedAt: "14:02 UTC · 1 hr ago",
      service: "property-agent-api",
      owner: "Agency Operations",
      affected: "p95 latency increased from 120ms to 690ms",
      diagnoses: [
        { id: "DX-2849-A", title: "Synchronous metrics file I/O blocks requests", summary: "Every counted response serializes and replaces the full metrics snapshot while holding a process lock, adding filesystem latency to request completion.", confidence: 0.78, evidenceIds: ["E1", "E2", "E4"], signals: ["Latency tracks snapshot duration", "Metrics route excluded and unaffected", "CPU remains normal"] },
        { id: "DX-2849-B", title: "Database query slowdown", summary: "CockroachDB latency is mildly elevated but does not explain the delay after responses have already been created.", confidence: 0.36, evidenceIds: ["E3"], signals: ["DB p95 only slightly higher", "Delay occurs in middleware finalization"] },
      ],
      suggestedChanges: [
        { id: "CH-46", diagnosisId: "DX-2849-A", title: "Move snapshot writing off the request path", detail: "Update counters quickly in memory and flush snapshots on a bounded background cadence.", risk: "Medium", category: "Code", files: ["PropertyCasualtyInsuranceAgentInfo/backend/metrics.py", "PropertyCasualtyInsuranceAgentInfo/backend/main.py"], implementation: "Keep counter mutation under the lock, but serialize and atomically replace the JSON snapshot from a periodic background task using a copied snapshot.", language: "python", code: `def record(self, method, route, status_code):\n    with self._lock:\n        self._update_counters(method, route, status_code)\n        self._dirty = True  # periodic flusher writes the snapshot`, validation: "Run concurrent CRUD traffic with an injected 300ms file-write delay and verify request p95 no longer follows filesystem latency.", rollback: "Restore synchronous writes if snapshot freshness or shutdown flushing cannot be guaranteed." },
        { id: "CH-47", diagnosisId: "DX-2849-A", title: "Measure snapshot write duration", detail: "Add a bounded metric for flush duration and failures without recursively invoking the same snapshot writer.", risk: "Low", category: "Observability", files: ["PropertyCasualtyInsuranceAgentInfo/backend/metrics.py"], implementation: "Log aggregate flush duration and error counts through the application logger, excluding raw metric payloads.", validation: "Make the log directory temporarily read-only in staging and verify a clear flush error without a recursive write loop.", rollback: "Remove the instrumentation if it creates excessive log volume." },
      ],
      similarIncidents: [
        { id: "INC-1842", title: "Audit file writer serialized API responses", similarity: 0.84, resolution: "Buffered writes and flushed outside the request lifecycle.", age: "4 months ago" },
      ],
      evidence: [
        { id: "E1", time: "14:01:51", source: "request.trace", detail: "Response created at +112ms; metrics middleware completed at +681ms", tone: "warning" },
        { id: "E2", time: "14:01:51", source: "filesystem.trace", detail: "Synthetic metrics JSON replace duration=563ms", tone: "critical" },
        { id: "E3", time: "14:01:50", source: "database.metrics", detail: "Cockroach query p95 increased by 34ms", tone: "info" },
        { id: "E4", time: "14:00:42", source: "api.metrics", detail: "GET /api/metrics latency stable because route is excluded from recording", tone: "info" },
      ],
    },
  },
  {
    incidentId: "INC-2846",
    title: "Active-agent picker returns no assignments",
    application: "InsuranceCallCenter",
    environment: "Staging",
    severity: "SEV-3",
    symptom: "The call-center UI loads contacts but the assigned-agent dropdown is empty.",
    reviewStatus: "pending",
    diagnosisCount: 2,
    topConfidence: 0.88,
    createdAt: "2026-09-04T13:19:00Z",
    payload: {
      dataOrigin: "synthetic",
      sourceProject: "InsuranceCallCenter + PropertyCasualtyInsuranceAgentInfo",
      scenarioBasis: "Modeled from the real shared CockroachDB boundary where the call center reads active agents owned by the sibling agent-management project.",
      detectedAt: "13:19 UTC · 1 hr 49 min ago",
      service: "insurance-call-center-api",
      owner: "Call Center Platform",
      affected: "All new contact assignments in staging",
      diagnoses: [
        { id: "DX-2846-A", title: "Sibling applications point to different databases", summary: "The call center is healthy against an empty staging cluster while agent management populated a different CockroachDB database.", confidence: 0.88, evidenceIds: ["E1", "E2", "E4"], signals: ["cc tables contain contacts", "insurance_agents count is zero", "Database hosts differ by deployment"] },
        { id: "DX-2846-B", title: "Agent status values do not match Active filter", summary: "The call-center query intentionally filters status='Active'; unexpected casing or status migration could hide rows, but the queried cluster contains no agent rows at all.", confidence: 0.29, evidenceIds: ["E3"], signals: ["Query predicate is exact", "No unfiltered rows found"] },
      ],
      suggestedChanges: [
        { id: "CH-44", diagnosisId: "DX-2846-A", title: "Validate the shared database target", detail: "Compare non-secret connection identity at startup and fail readiness if the required insurance_agents table or active rows are absent.", risk: "Low", category: "Configuration", files: ["InsuranceCallCenter/backend/database.py", "InsuranceCallCenter/backend/services.py"], implementation: "Expose a sanitized database cluster/database identifier and a read-only dependency check for the sibling-owned table. Do not create or mutate insurance_agents from the call-center app.", language: "python", code: `active_agents = database.execute(\n    select(func.count()).select_from(insurance_agents)\n        .where(insurance_agents.c.status == "Active")\n).scalar_one()`, validation: "Point both staging applications to the intended cluster and confirm the known synthetic agents appear without the call center writing their table.", rollback: "Restore the prior call-center DATABASE_URL if the target database identity is incorrect." },
        { id: "CH-45", diagnosisId: "DX-2846-B", title: "Alert on empty assignment catalog", detail: "Warn when the active-agent dependency changes from non-empty to empty.", risk: "Low", category: "Observability", files: ["InsuranceCallCenter/backend/services.py"], implementation: "Emit one low-cardinality gauge for active agent count and an application warning on a nonzero-to-zero transition.", validation: "Use a test database with zero and then one Active agent and confirm the gauge and API response follow the table.", rollback: "Remove the warning if planned empty environments make it noisy." },
      ],
      similarIncidents: [
        { id: "INC-1730", title: "Reporting service connected to empty tenant database", similarity: 0.9, resolution: "Added sanitized database identity and dependency readiness checks.", age: "6 months ago" },
      ],
      evidence: [
        { id: "E1", time: "13:18:52", source: "call-center.access", detail: "GET /api/agents/options returned 200 with zero items", tone: "warning" },
        { id: "E2", time: "13:18:38", source: "database.query", detail: "SELECT count(*) FROM insurance_agents returned synthetic value 0", tone: "critical" },
        { id: "E3", time: "13:18:20", source: "source", detail: "Assignment query filters sibling-owned rows where status equals Active", tone: "info" },
        { id: "E4", time: "13:15:07", source: "deployment", detail: "Sanitized database identity differs between the two staging applications", tone: "critical" },
      ],
    },
  },
];
